- name: dkdkad
  hosts: db_hosts
  become: yes
  become_method: sudo

  tasks:
    - name: "Install general packages"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql-15
        - postgresql-contrib
        - net-tools

    - name: "Settings master"
      import_tasks: task-master.yml
      when: "'db_master' in group_names"

    - name: "Settings slave"
      import_tasks: task-slave.yml
      when: "'db_slave' in group_names"

    - name: "Finally"
      import_tasks: finally.yml
      when: "'db_master' in group_names"
      become_user: "{{ ansible_user }}"

    - name: "Start Bot"
      shell:
        chdir: /home/user/bot
        cmd: "../venv/bin/python main.py >/dev/null 2>&1 &"
      when: "'db_master' in group_names"

  handlers:
    - name: Restart db
      systemd:
        state: restarted
        name: postgresql

